### ISSUE TITLE
missing dependency - com.bytezone.common

### ISSUE THREAD

**Issue by pantinor** [dmolony/DiskBrowser#1]
I was attempting to use it, seems interesting.  But the ui package has problems compiling due to missing dependency for "com.bytezone.common" package classes.

**Comment by dmolony** [comment]
The DiskBrowser.jar file is all you need to use the program. If you want to compile it you will also need InputPanel.jar and Common.jar, which I have just added to the latest release.

**Comment by pantinor** [comment]
Thanks!  works great.
