### ISSUE TITLE
Running DiskBrowser on macOS X Mojave 10.14 

### ISSUE THREAD

**Issue by Tiza59** [dmolony/DiskBrowser#10]
Hi Denis,

I would suggest to give a hint to macOS X users that jarlauncher included with theirs systems may not work. Opening DiskBrowser from the Terminal works much better.
Kind regards
Uwe

P.S. Have you seen that the German Computer Magazine c't (https://www.heise.de/ct/) did recommends your application for Apple II fans. Drop me an Email if you want the magazine or the article (uwefalck@mac.com).

**Comment by dmolony** [comment]
Hi Uwe

I'm not sure what you mean. Double-clicking on the jar file on MacOS works on my machine. The installation instructions already say to use the latest version of java.

Cheers

Denis

**Comment by Tiza59** [comment]
Thank you, I´ll try to fix my java installation.
