### ISSUE TITLE
Feature Request: Support Total Replay packed artwork

### ISSUE THREAD

**Issue by roughana** [dmolony/DiskBrowser#12]
The Total Replay build process incorporates Exomiser packing of art files to reduce space on disk. These packed files cannot be displayed by DiskBrowser.

The Total Replay make file includes the following relevant lines:
rem https://bitbucket.org/magli143/exomizer/wiki/Home
set EXOMIZER=exomizer mem -q -P23 -lnone

:compress
for %%q in (res\action.dhgr.uncompressed\*) do if not exist res\action.dhgr\%%~nxq %EXOMIZER% res\action.dhgr.uncompressed\%%~nxq@0x4000 -o res\action.hgr\%%~nxq
for %%q in (res\action.hgr.uncompressed\*) do if not exist res\action.hgr\%%~nxq %EXOMIZER% res\action.hgr.uncompressed\%%~nxq@0x4000 -o res\action.hgr\%%~nxq
for %%q in (res\artwork.shr.uncompressed\*) do if not exist res\artwork.shr\%%~nxq %EXOMIZER% res\artwork.shr.uncompressed\%%~nxq@0x2000 -o res\artwork.shr\%%~nxq
cscript /nologo bin\buildfileinfo.js res\TITLE.HGR "06" "4000"
cscript /nologo bin\buildfileinfo.js res\TITLE.DHGR "06" "4000"
cscript /nologo bin\buildfileinfo.js res\ACTION.HGR "06" "3FF8"
cscript /nologo bin\buildfileinfo.js res\ACTION.DHGR "06" "3FF8"
cscript /nologo bin\buildfileinfo.js res\ACTION.GR "06" "6000"
cscript /nologo bin\buildfileinfo.js res\ARTWORK.SHR "06" "1FF8"

**Comment by dmolony** [comment]
Hi Andrew

On the v3 copy I have of Total Replay the TITLE.HGR folder contains the following files:

AIRHEART
BAD.DUDES
BATMAN
BLOCKCHAIN
D.GENERATION
DEATH.SWORD
HEAVY.BARREL
HYPER.HEAD.ON
INDIANA.JONES
OOTW
PIPEDREAM
PLATOON
PRINCEUNP
QIX
RADWARRIOR
RAMPAGE
RENEGADE
ROBOCOP
SPIDERBOT
SUMMER.EDITION
THEXDER128K
VICTORY.ROAD
WINTER.EDITION

These files all take up 17 blocks and are all identical. That seems like a waste of 391 blocks.

I doubt that I will support an external 3rd-party library.

Cheers

Denis

**Comment by roughana** [comment]
This was deliberate to facilitate remaining in HGR mode for every title.
The situation changed with V4 as the DHGR titles can now be displayed as the interface changed to support DHGR.
There are some GR and DGR titles that still have this treatment but there are fewer of them.
I’ve pointed this out as a potential area that could yield some space.

Regards,
Andrew

**Comment by roughana** [comment]
I've asked Qkumba if he knows of java code that can extract exomiser compression.

**Comment by dmolony** [comment]
Is the exomiser file format available?

**Comment by roughana** [comment]
Source in C exists for an unpacker. Perhaps that would be useful to refer to.

I think exodecr would be the tool required for accessing Total Replay crunched data.

Note from the author of Exomizer below.

Regards
Andrew

> Hi, Just wondering if you are aware of an implementation of the Exomiser unpacking algorithm in Java or perhaps C ?

I do not know of any decompessor in java. However, there are two in C included in the distribution in the rawdecrs folder that decompresses data created by the exomizer raw command.

rawdecrs/exodecrunch.[ch] and rawdecrs/exodecr.[ch]

where exodecr is a traditional push flow decompressor (one method call decrunches a file to a given buffer) and exodecrunch is a pull flow decompressor (you call a method several times to get the next decmpressed byte).

/Regards

Magnus Lind

**Comment by dmolony** [comment]
Hi Andrew

Did you compare the compressed file sizes to any other compression routines? Is it a huge improvement over, say, PackBytes? Because there’s no way I will be asking people to download a dependency, and I really hate reading other people’s C code. If the format is documented I would implement it.

**Comment by dmolony** [comment]
The other reason I’m not interested in supporting exomiser format is that yours is the only disk I know of that plans to use it. I think any non-apple compression is a bad choice, and I question whether any compression at all is required. You will never fit every program on a single image, so at some stage you will be forced to split Total Replay over two (or more likely more) images. I don’t see the benefit in squeezing a few more games onto one image at the expense of packing and multiple unpacking. And forcing DiskBrowser and CiderPress and who knows what else to adapt.

I’m happy to wait for Total Replay V6 Disk 1 and Total Replay V6 Disk 2, when you go back to not compressing anything.

**Comment by roughana** [comment]
Apparently the decompression time is faster than loading raw assets from disk. The use of exomiser is prolific through qkumba's ProDOS ports because it has the best compression and is quick to unpack in 6502 asm.
But I understand your position. Thanks for considering it.

**Comment by dmolony** [comment]
Andrew can you contact me directly? I have some questions about exomiser.

**Comment by dmolony** [comment]
It's working now, but I'm not completely happy about the binary file not having some kind of indentifier. How can I tell exomizer files apart from ordinary binary files?

**Comment by roughana** [comment]
I don't have any contact for you and I don't know how to identify exomizer files.

**Comment by roughana** [comment]
For posterity: Discussion continued via email.
Support for the Exomiser format for Total Replay was implemented and then removed. 
This release supports it: [https://github.com/dmolony/DiskBrowser/releases/download/1.46/DiskBrowser.jar](url)
