### ISSUE TITLE
repo is unbuildable : no build system file and missing subtree

### ISSUE THREAD

**Issue by wsourdeau** [dmolony/DiskBrowser#13]
Hi,

There is no build file anywhere. As I only have Java 11 on my system, I would have liked the possibility of building this package and there is no easy way without a maven, ant or any other build system build file. Is it possible for you to provide one?

Also, there seems to be at least one missing package. The only provided subtree is com.bytezone.diskbroswer but it depends on com.bytezone.input which is missing.

I cannot wait to try your utility. Thank you!

**Comment by dmolony** [comment]
I don’t think it will work with java 11.

**Comment by dmolony** [comment]
The missing package is in the earlier releases. It almost never changes, so I don't include it with every release.

My build file is completely trivial. I suggest you just compile it, or load it into an IDE.
