### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by wyatt-wong** [dmolony/DiskBrowser#14]
How do I build from source in macOS ?

**Comment by dmolony** [comment]
This is the relevant part of my ant file:

<target name="jar" depends="compile">
  <jar destfile="${jarFile}">
    <fileset dir="${binDir}" />
    <zipfileset src="${dropbox}/InputPanel.jar" />
    <manifest>
      <attribute name="Main-Class" value="com.bytezone.diskbrowser.gui.DiskBrowser" />
    </manifest>
  </jar>
</target>

**Comment by wyatt-wong** [comment]
Can you include the necessary files in the package for building from source. I can't find any Makefile or configure file in the source package.

**Comment by dmolony** [comment]
There is no makefile or configure file. I have just given you the relevant ant file step.

**Comment by wyatt-wong** [comment]
Never mind then. I will look for other tools.

**Comment by dmolony** [comment]
Great idea.
