### ISSUE TITLE
Folders missing

### ISSUE THREAD

**Issue by WizardOfWor1969** [dmolony/DiskBrowser#15]
When trying to add a HOME directory. A directory with subdirectories does not show those subdirectories for selection.

**Comment by dmolony** [comment]
I just tried it and it works. Can you give me more information?

**Comment by WizardOfWor1969** [comment]
The Documents folder has a folder in it called Apple II Disks, and that does not show up. As you can see in fact no subfolders show up and there are around 50 or so subfolders in that directory. Some other directories do show contents, so perhaps it is a permission problem? I am never prompted for permission to open a directory.

![Screen Shot 2021-01-07 at 11 33 43 PM](https://user-images.githubusercontent.com/52321250/103982925-a2bdbd80-5141-11eb-82a8-4d89b200b4a7.png)

**Comment by WizardOfWor1969** [comment]
BTW- This is my Security & Privacy settings->File And Folders for Java... Don't know how to add an additional folder (like Documents), but seems like a security nightmare as you can not specify by Jar file. Other folders do show up in your app outside of Downloads and Desktop , so it is a bit of a mystery to me why Documents does not.
![Screen Shot 2021-01-07 at 11 42 27 PM](https://user-images.githubusercontent.com/52321250/103983321-473fff80-5142-11eb-87f0-1f892d66da29.png)

**Comment by dmolony** [comment]
That’s an interesting problem, that I don’t have the answer to. DiskBrowser has no control over what appears in your file dialogs.

As you suggest, it must be a security/permissions issue. Sorry I don’t know any more.

**Comment by WizardOfWor1969** [comment]
It must be a Java thing, that dialog saying File:Documents is not a native dialog on Mac. It would be nice to be able to just type in the path you want to set (like in a preferences pane) as an alternative.

**Comment by dmolony** [comment]
I would try adding a new folder via the dialog you sent, and see if that triggers a permissions change. Also try a test folder outside your Documents folder.

**Comment by WizardOfWor1969** [comment]
Creates the folder I double checked it.  No security or permissions prompt, but the browser continues to show nothing. I wonder if their is a file name problem here as I am able to browse other directories.

**Comment by dmolony** [comment]
These are my current security settings:



Firstly, I don’t know why you don’t have the Documents Folder listed. However I removed all permissions and tried to set my home folder to the Documents folder and this appeared:




So it looks like a MacOS issue. Are you using Big Sur?
