### ISSUE TITLE
Wizardry 1

### ISSUE THREAD

**Issue by IngisKahn** [dmolony/DiskBrowser#16]
I have a WIZ1.DSK file for PC that is not recognized, is that out of scope for this project?
I've been looking for Tommy's Wiz1WizardryPascal.txt and Wiz1StartupPascal.txt or any info on Wizardry's SYSTEM.INTERP to no avail.

**Comment by dmolony** [comment]
This project can only view disk files suitable for the Apple II series.

Are these the files you are looking for?
[Wiz1StartupPascal.txt](https://github.com/dmolony/DiskBrowser/files/6025985/Wiz1StartupPascal.txt)
[Wiz1WizardryPascal.txt](https://github.com/dmolony/DiskBrowser/files/6025987/Wiz1WizardryPascal.txt)

**Comment by IngisKahn** [comment]
Wow, those are the files, thanks.  I'm writing a Pascal decompiler, but I see Tommy beat me to the punch 7 years ago :)
