### ISSUE TITLE
Compiling project from source

### ISSUE THREAD

**Issue by ericjung** [dmolony/DiskBrowser#17]
Hi,

I've cloned the git repo and am trying to compile the project from source. The entire `com.bytezone.input` package and its classes do not exist. Can you add them to git, or are they proprietary?

Thank you.

p.s. going through closed issues, i see others have requested this before (e.g. issue 13). If you don't want to add it to the repo, I understand, but can you at least point me to those sources in a previous branch or release? (Sources preferred to binary jar files because I'm trying to understand your project in entirety, if that's ok). I am both a long-time Java dev, since the 1990s, and also an original Apple 2e owner -- so our paths cross :)

**Comment by dmolony** [comment]
Hi

Because that class rarely changes I don’t include it with every release. If you go back through the recent releases you will find the latest jar.

**Comment by ericjung** [comment]
@dmolony thanks for the reply, which I think is what you said in issue 13. When you say 'you will find the latest jar', do you mean:

1. The latest jar with source include or just a binary?
2. Since the current release is named DiskBrowser.jar, do you mean download an older DiskBrowser.jar release, and look for a jar embedded within it? Or .class files for `com.bytezone.input`?

Also: any chance of support MagicWindow files natively? MagicWindow was a popular word processor.

**Comment by dmolony** [comment]
See V1.51 on the releases page. It has InputPanel.jar.

I’ve never heard of MagicWindow. Is there a reference anywhere?

**Comment by dmolony** [comment]
I found some MagicWindow disks, I’ll have a look.

**Comment by ericjung** [comment]
@dmolony There's various info on the web; [for example](http://www.artscipub.com/history/magicwindow/):

`The Magic Window master disk boots in a single step on any Apple II system -13or 16-sector. If a language card or compatible RAM card is installed in slot #0, the program will load there ...
...
Another major advantage of Magic Window is that it reads and writes files in standard DOS 3.2 format. | Another major advantage of Magic Window is that it reads and writes files in standard DOS 3.2 format.`

**Comment by dmolony** [comment]
It seems to be working, but I'll need to do more testing.

**Comment by ericjung** [comment]
I can also test if you want -- I have a large corpus of original Magic Window files from my own collection. Just push your work to a branch if you want me to try anything.

**Comment by dmolony** [comment]
I have pushed the (very minor) change already, so if you are building from source you will already have it.

**Comment by dmolony** [comment]
I don’t have any prodos disks with .MW files. Do you have any?

**Comment by ericjung** [comment]
Probably not prodos -- I did not use prodos much. Just DOS 3.x with lots of .mw files on lots of different .dsk images. Can you work with those?

**Comment by dmolony** [comment]
I have the three Dos disks from Asimov - that should be enough.

**Comment by ericjung** [comment]
I've built your latest commits and am running with JDK 11.x. I've opened 3 different .mw files and they look great so far.

**Comment by dmolony** [comment]
That’s great.

Just so you know, I expect to be using some of the new Java 16 features in the future. You may want to install that too.

**Comment by ericjung** [comment]
Thanks -- I have it installed just not in the path yet. Thanks for the print feature. This is really unbelievable. Coupled with the MagicWindows support, I can print old documents on modern devices.

Is application support pluggable in any way? I ran a BBS in the 80s, a modified version of AppleNet BBS which kept the file format. So I'm wondering if I could add support for 'message' files if I reverse engineered the file format.

**Comment by dmolony** [comment]
Most of the files in com.bytezone.diskbrowser.applefile deal with a single file format. You just need to extend AbstractFile and override getText(). See MagicWindowText.java for a fairly minimal example.

If the file is recognisable then I make an entry in com.bytezone.diskbrowser.dos.AbstractCatalogEntry.java and com.bytezone.diskbrowser.prodos.FileEntry.java. So sort of pluggable.

I’m surprised printing still works, it’s a real pain from java. I usually just copy the text into something else and print from there.
