### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kaimex** [dmolony/DiskBrowser#18]
Hi Denis,
this is a nice program...
however, I am missing very much a possibility to export files from the virtual Apple disks to files on the PC.
Could you please consider to implement such a function ? 
I have also tried to capture high-lighted output from the middle window  with CTRL-C and to paste it into NotePad or a Program for Hex-File editing. Sometimes it works, sometimes not. 
Some of the original Apple files contain a mixture of ASCII code and raw integer numerical values including zeros. My impression is, that in such cases copy & paste  of a high lighted section of the window contents only delivers a fraction from the beginning up to the next zero.
So in these cases copy/paste of the fully marked window does not work.
Best Regards
Kai

**Comment by dmolony** [comment]
Hi Kai

That's a good idea. I have a working version, but I need to do some more testing. It will be in the next release.

Cheers

Denis
