### ISSUE TITLE
Feature request: Write to a DSK from PC

### ISSUE THREAD

**Issue by kaimex** [dmolony/DiskBrowser#19]
Hi Denis,

have you ever thought about writing files from the PC to an Apple ][ DSK (DOS 3.3) ?
If you think it could be done, I would very much like to be able to write binary object files  in the BSAVE/BLOAD format with added load address and length, such that I can BLOAD them in AppeWin. I could also provide the object file with already added address and length.

Thank you again for your very useful program
regards Kai

**Comment by dmolony** [comment]
I'm not exactly sure what you are asking for. I cannot write directly to a floppy disk, but I think AppleWin will allow you to paste data directly into memory. Then you just have to BSAVE it.

**Comment by kaimex** [comment]
Hi Denis,
I meant writing to a DOS3.3 Floppy Disk image file of type *.dsk .
In the meantime I have found that this is possible with "AppleCommander", another tool written in java.
I do not know about a way to paste data from a PC disk file into the simulated Apple's memory in AppleWin.
Thank you again
Kai
