### ISSUE TITLE
Feature Request: Apple 3 Pascal Disk

### ISSUE THREAD

**Issue by Tiza59** [dmolony/DiskBrowser#20]
Hi Denis,

what do you think of making Apple /// disk images as accessible as Apple ][ disk images? As you support Prodos already, which is an Apple ][ port of Apple /// SOS, disks show up already flawlessly. There seems to be a little piece of code missing to let your pCode disassembler acting on Apple 3 pascal code files. See the enclosed screenshot.

Thank you very much for your hard work and your useful utility.
Kind regards Uwe

<img width="1208" alt="Bildschirmfoto 2022-01-31 um 11 56 30" src="https://user-images.githubusercontent.com/16560008/151783339-fce122de-fa28-4382-91e8-d2bb4ef2dd35.png">

**Comment by dmolony** [comment]
Hi Uwe

I’m not sure I understand what you’re asking for.

I’m happy to look at making Apple /// disk images accessible, but I don’t have any to try out. Is the disk in your screenshot an Apple /// disk image?

Cheers

Denis

**Comment by Tiza59** [comment]
Exactly, Apple /// images are mounted already as shown, but Apple /// pCode files are disassembled as 6502 code. I will include the disk image above and I have hundreds of images in case you want more. I had to change the extension from .DSK to .TXT to upload it to Github. Please change it back to .DSK. Regards Uwe

[Backup3.TXT](https://github.com/dmolony/DiskBrowser/files/7970324/Backup3.TXT)

**Comment by dmolony** [comment]
So what you're asking for is that DiskBrowser be able to interpret PDA, SOS and PCD file types? Do you have any documentation on them?

**Comment by Tiza59** [comment]
Yes, I'm able to guide you to documentation on these filetypes, please check apple3.org. I will answer any remaining questions. As a first shot, PDA and SOS is 6502 assembler, so you interpret these already. PCD files is pretty much the same als Apple ][ pCode files, same segment dictionary, higher segment numbers are possible, pretty much same pCode.

**Comment by dmolony** [comment]
I've done as much as I can for now, so I'm going to close this issue.

**Comment by Tiza59** [comment]
Thanks a lot, will test it over the weekend. Cheers
