### ISSUE TITLE
java.time.DateTimeException when loading Pascal image

### ISSUE THREAD

**Issue by einstein95** [dmolony/DiskBrowser#21]
Attempting to load any Pascal-formatted image with a file last modified in January of a year gives
(if the image is .woz)
```
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
```
(if the image is .dsk)
```
Exception in thread "AWT-EventQueue-0" java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
```
The trace dump points to https://github.com/dmolony/DiskBrowser/blob/036e47b9b1bf4c29d7c7a0b9ebc3ff80ab21ab7b/src/com/bytezone/diskbrowser/utilities/Utility.java#L447

To replicate, try loading any Wizardry 1-3 boot disk

**Comment by dmolony** [comment]
I think it's fixed now, try the new release.

**Comment by einstein95** [comment]
Yup, can confirm it's fixed
