### ISSUE TITLE
Feature Request: Export files as formatted files

### ISSUE THREAD

**Issue by einstein95** [dmolony/DiskBrowser#23]
Basically, export tokenized BASIC files as text, and prodos text files as plaintext files. Currently having to copy/paste from the formatted window which loses proper tab indenting and is a pain when working with multiple files.

**Comment by dmolony** [comment]
I will have a look at saving files in their formatted state.
Copy/paste works fine for me, the tabs are not lost. Perhaps it depends on the settings of the program which you are pasting it into?

**Comment by dmolony** [comment]
Have added a 'formatted' option to the save dialog. Will be in the next release.
