### ISSUE TITLE
DiskBrowser misses TSList if Catalog also claims the sector

### ISSUE THREAD

**Issue by greg-kennedy** [dmolony/DiskBrowser#25]
Discovered this issue with the 4am crack of "The Oregon Trail 1.4", side A, available here: https://archive.org/details/MECC_A157_v14_4amCrack

The issue is that OREGON.IMA is listed in the catalog, but DiskBrowser shows it as 0 sectors length.

What happened is that CATALOG sector at track 11, sector 9 lists the next entry at track 11, sector 8.  However, THAT sector is actually the TSList for OREGON.IMA - not a CATALOG entry at all.  (Well, it seems to work as both - when read as CATALOG it looks empty, when read as TSList it contains the sectors for OREGON.IMA)

This causes DiskBrowser to also show OREGON.IMA's sectors to be orphaned (those for track 11, sectors 1 through 7 plus the TSList at 8).

I'm not sure how best this would be fixed, it seems as though you need almost a "shared" half-filled box where a sector can do double-duty as both CATALOG and TSList.  Real hardware presumably doesn't care as it'll be read in whichever mode it's operating in.

**Comment by dmolony** [comment]
A quick fix would be to alter the bytes in sector 11/09 from 11 08 to 00 00.

But I will give some thought on how to spot this automatically.

I wonder if the cracking procedure is at fault here?

**Comment by dmolony** [comment]
I believe this is an issue for 4am.
