### ISSUE TITLE
Wishlist: operate directly on files in Output window. 

### ISSUE THREAD

**Issue by hackerb9** [dmolony/DiskBrowser#26]
DiskBrowser is great and solved my problem. I do have a suggestion or two, if you are open to ideas. 

Currently, DiskBrowser starts out showing a list of files on a disk in the Output window, but cannot actually display, save, or otherwise operate on those files until the user double-clicks on the name of the disk image in the Catalog window. After that, the  Catalog window shows the list of files which the user can click on to show formatted views of the files. 

It would be nice if the user did not have to double-click on the disk image to start examining files. There are many possible solutions, but the cleanest would be to let the user click on the filename in the Output window and have that automatically show the contents.

If that is too complicated to implement, another way would be to let users right-click on files in the Output window to pop up a context menu. It could offer options like, "Save file", "Display Formatted Text View", "Display Hex dump", and "Open in Default App". 

Thanks again for the useful program!

**Comment by dmolony** [comment]
I agree with your observation, and have addressed it in the new version. I hope to release it in 2024. See the listing for DiskBrowser ][.
