### ISSUE TITLE
Please support Agat 840K disk images with DOS 3.3 filesystem

### ISSUE THREAD

**Issue by shattered** [dmolony/DiskBrowser#3]
840K disks were used by Agat (a Soviet workalike of Apple II) -- https://github.com/sintech/AGAT/blob/master/docs/agat-840k-format.txt and http://www.torlus.com/floppy/forum/viewtopic.php?f=19&t=1385

Sector-level images are 860160 bytes in size, geometry is 80x2x21x256.

**Comment by dmolony** [comment]
Noted.
