### ISSUE TITLE
com.bytezone.common package not commited?

### ISSUE THREAD

**Issue by cybernesto** [dmolony/DiskBrowser#4]
I had the hope to contribute a bit to your project but the com.bytezone.common package is missing and I am not able to build. Is it not being commited or am I missing something?

**Comment by dmolony** [comment]
Hi

The common jar is just a bunch of routines that I use in several projects. I sometimes include it on github just so people can build the project. Would you like the latest jar file, or do you want the source as well?

Also I haven't worked on DiskBrowser for a while as I am rewriting it.

Denis

**Comment by cybernesto** [comment]
The jar file is enough, I don't think I need to do any changes there.
I think it would be fair to include it somehow in the repository.

**Comment by dmolony** [comment]
There are now two extra jars in release 1.0.24.
