### ISSUE TITLE
DiskBrowser does not recognize WOZ files

### ISSUE THREAD

**Issue by BeWe60** [dmolony/DiskBrowser#8]
DiskBrowser does not recognize WOZ files created with the current Applesaucefdc. What am I doing wrong?
![2019-02-21_05-14-46](https://user-images.githubusercontent.com/47841913/53143716-80e0df00-3599-11e9-8afe-37ba9de237d6.jpg)

**Comment by dmolony** [comment]
Probably nothing if it's a woz2 disk. I haven't updated DiskBrowser for that version yet.

If you send me the disk I'm happy to take a look at it.

**Comment by BeWe60** [comment]
Thank you very much for the quick feedback. In the appendix are two WOZ images.
[WOZ Images.zip](https://github.com/dmolony/DiskBrowser/files/2887724/WOZ.Images.zip)

**Comment by dmolony** [comment]
Those two disks are both in WOZ2 format, which is not supported yet. It should be available in the next release.

Cheers

Denis

**Comment by dmolony** [comment]
Woz 2 is now supported. However most disks in Woz format are copy-protected, so it doesn't make much sense to use them with DiskBrowser.
